name       : gtick
version    : 0.5.5
release    : 2
source     :
    - https://www.antcom.de/gtick/download/gtick-0.5.5.tar.gz : e24331b2c903557b2a7d863cfef04dfe7624ee3d62861bfd06dd4317ee7bdc48
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A metronome application
description: |
    GNU GTick is a metronome application supporting different meters (Even, 2/4, 3/4, 4/4 and more) and speeds ranging from 10 to 1000 bpm.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(sndfile)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
