name       : gtick
version    : 0.5.4
release    : 1
source     :
    - https://www.antcom.de/gtick/download/gtick-0.5.4.tar.gz : 409439e231892ffcfafc8d06a713c0f8c7e333920e1b885817d36e096db2fa7c
license    : GPL-3.0
component  : multimedia.audio
summary    : A metronome application
description: |
    GNU GTick is a metronome application supporting different meters (Even, 2/4, 3/4, 4/4 and more) and speeds ranging from 10 to 1000 bpm.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(sndfile)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
